import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthGuard from "@/src/components/AuthGuard";
import { Toaster } from "react-hot-toast";
import AboutUs from "@/src/components/AboutUs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
        <body>
          <AuthGuard>
            {children}
          </AuthGuard>
          <AboutUs />
        <Toaster
          position="top-right"
          reverseOrder={false}
        />
        </body>
      </html>
    );
}
